name: Build and deploy nfasit-frontend

on: 
  push:
    branches: 
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/fasit-frontend:${{ github.sha }}

jobs:
  build:
    name: Checkout code and setup node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.9.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-cache-
      - name: build and test
        run: |
           mkdir -p /tmp/docker/dist
           cp production_server.js config.js selftest.js package.json package-lock.json /tmp/docker/dist
           cd /tmp/docker/dist && npm ci --production && cd -
           npm ci && npm run test && npm run build || exit 1 # Creating frontend bundle
           cp -r dist /tmp/docker/dist
           cp Dockerfile /tmp/docker
      - name: Build docker image
        run: docker build --tag $IMAGE /tmp/docker
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_REPOSITORY" --password-stdin
      - name: Push docker image
        run: docker push $IMAGE

  deploy-dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator.yaml
          VARS: .nais/dev-config.json
          OWNER: navikt
          REPOSITORY: fasit-frontend
  deploy-prod:
    name: Deploy to prod-gcp
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/naiserator.yaml
          VARS: .nais/prod-config.json
          OWNER: navikt
          REPOSITORY: nais-deploy